# comands:
# docker build -t <nombre_image:tag> .
# docker run --name <nombre_para_contenedor> -p <puerto_host>:<puerto_contenedor> <nombre_imagen>

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["AutorsServices.API/AutorsServices.API.csproj", "AutorsServices.API/"]
COPY ["AutorsServices.BLL/AutorsServices.BLL.csproj", "AutorsServices.BLL/"]
COPY ["AutorsServices.DAL/AutorsServices.DAL.csproj", "AutorsServices.DAL/"]
RUN dotnet restore "./AutorsServices.API/AutorsServices.API.csproj"
COPY . .
WORKDIR "/src/AutorsServices.API"
RUN dotnet build "./AutorsServices.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./AutorsServices.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AutorsServices.API.dll"]